export interface Property {
  id: number;
  title: string;
  location: string;
  image: string;
  minPrice: number;
  maxPrice: number;
  highestBid: number;
  highestBidder: string;
  minimumIncrement: number;
  bidsCount: number;
  timeRemaining: string;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  yearBuilt: number;
  description: string;
  features: string[];
  recentBids: Array<{ bidder: string; amount: number; time: string }>;
}

export const allProperties: Property[] = [
  { id: 1, title: "Historic Colonial Estate", location: "123 Maple Street, Boston, MA", image: "https://cdn.b12.io/client_media/MMT7mwJl/fff1a671-4fe9-11f1-a7fe-0242ac110002-zhuJvn7mf0gTUgvcPhEDJ.jpg", minPrice: 450000, maxPrice: 550000, highestBid: 485000, highestBidder: "JSmith_Boston", minimumIncrement: 5000, bidsCount: 5, timeRemaining: "2 days 4 hours", bedrooms: 4, bathrooms: 3, sqft: 4200, yearBuilt: 1875, description: "This stunning historic colonial estate features original hardwood floors, grand staircase, and period details throughout. Recently updated systems and gourmet kitchen. Situated on 2 acres with mature landscaping.", features: ["4 Bedrooms", "3 Bathrooms", "4,200 Sq Ft", "2 Acres", "Historic Details", "Updated Systems", "Gourmet Kitchen", "Wine Cellar"], recentBids: [{ bidder: "JSmith_Boston", amount: 485000, time: "2 minutes ago" }, { bidder: "Property_Hunter", amount: 480000, time: "18 minutes ago" }, { bidder: "RealEstate_Pro", amount: 475000, time: "1 hour ago" }, { bidder: "BidMaster2024", amount: 470000, time: "3 hours ago" }, { bidder: "Property_Investor", amount: 465000, time: "6 hours ago" }] },
  { id: 2, title: "Modern Downtown Condo", location: "456 Urban Avenue, New York, NY", image: "https://cdn.b12.io/client_media/MMT7mwJl/ff33b314-4fe9-11f1-8cb6-0242ac110002-JK63ZlX3sQjT0pL-9OemR.jpg", minPrice: 750000, maxPrice: 850000, highestBid: 810000, highestBidder: "NYC_Investor", minimumIncrement: 10000, bidsCount: 8, timeRemaining: "5 days", bedrooms: 2, bathrooms: 2, sqft: 1800, yearBuilt: 2015, description: "Sleek modern condominium in the heart of downtown with floor-to-ceiling windows, open floor plan, and luxury finishes. Building amenities include gym, pool, concierge, and rooftop deck.", features: ["2 Bedrooms", "2 Bathrooms", "1,800 Sq Ft", "Floor-to-Ceiling Windows", "Gym Access", "Pool", "Concierge", "Rooftop Deck"], recentBids: [{ bidder: "NYC_Investor", amount: 810000, time: "30 minutes ago" }, { bidder: "CityDweller", amount: 800000, time: "2 hours ago" }, { bidder: "Urban_Professional", amount: 790000, time: "5 hours ago" }, { bidder: "Manhattan_Buyer", amount: 780000, time: "12 hours ago" }, { bidder: "Skyline_View", amount: 770000, time: "1 day ago" }] },
  { id: 3, title: "Luxury Waterfront Villa", location: "789 Coast Road, Miami, FL", image: "https://cdn.b12.io/client_media/MMT7mwJl/001fa7bc-4fea-11f1-883e-0242ac110002-9W6neFIs23imoQxaGYqK2.jpg", minPrice: 1200000, maxPrice: 1500000, highestBid: 1350000, highestBidder: "Luxury_Collector", minimumIncrement: 25000, bidsCount: 12, timeRemaining: "1 day 12 hours", bedrooms: 5, bathrooms: 4, sqft: 6500, yearBuilt: 2018, description: "Spectacular waterfront villa with private beach access, infinity pool, and panoramic ocean views. State-of-the-art smart home system, wine room, and spa facilities. Gated community with 24-hour security.", features: ["5 Bedrooms", "4 Bathrooms", "6,500 Sq Ft", "Private Beach", "Infinity Pool", "Smart Home", "Wine Room", "Spa", "24-Hour Security"], recentBids: [{ bidder: "Luxury_Collector", amount: 1350000, time: "1 hour ago" }, { bidder: "Waterfront_Investor", amount: 1340000, time: "3 hours ago" }, { bidder: "Coastal_Property", amount: 1325000, time: "8 hours ago" }, { bidder: "Beach_Lover", amount: 1310000, time: "12 hours ago" }, { bidder: "Premium_Buyer", amount: 1300000, time: "1 day ago" }] },
  { id: 4, title: "Modern Townhouse Complex", location: "321 Elm Street, Seattle, WA", image: "https://cdn.b12.io/client_media/MMT7mwJl/0048d943-4fea-11f1-8d68-0242ac110002-I1JHLwvta0nclkumTk7No.jpg", minPrice: 600000, maxPrice: 700000, highestBid: 650000, highestBidder: "Seattle_Buyer", minimumIncrement: 5000, bidsCount: 3, timeRemaining: "8 days", bedrooms: 3, bathrooms: 2, sqft: 2400, yearBuilt: 2020, description: "Brand new townhouse with contemporary design, energy-efficient systems, and modern amenities. Located in walkable neighborhood with parks, shops, and restaurants nearby.", features: ["3 Bedrooms", "2 Bathrooms", "2,400 Sq Ft", "Modern Design", "Energy Efficient", "Garage", "Deck", "Walkable Neighborhood"], recentBids: [{ bidder: "Seattle_Buyer", amount: 650000, time: "4 hours ago" }, { bidder: "Pacific_Home", amount: 645000, time: "1 day ago" }, { bidder: "Northwest_Investor", amount: 640000, time: "2 days ago" }] },
  { id: 5, title: "Commercial Office Tower", location: "100 Business Plaza, Chicago, IL", image: "https://cdn.b12.io/client_media/MMT7mwJl/ff2d4dc9-4fe9-11f1-b78a-0242ac110002-kyqw6DL7_N3sGwGFN1-L4.jpg", minPrice: 5000000, maxPrice: 6000000, highestBid: 5500000, highestBidder: "Corporate_Investor", minimumIncrement: 50000, bidsCount: 6, timeRemaining: "3 days", bedrooms: 0, bathrooms: 0, sqft: 35000, yearBuilt: 2010, description: "Prime commercial office tower in Chicago's central business district. LEED certified, modern facilities, and high-quality tenancy. Strong investment opportunity with long-term leases.", features: ["35,000 Sq Ft", "LEED Certified", "Modern Facilities", "High-Quality Tenants", "Parking Available", "Conference Centers", "Cafeteria", "Rooftop Garden"], recentBids: [{ bidder: "Corporate_Investor", amount: 5500000, time: "5 hours ago" }, { bidder: "Commercial_Partners", amount: 5450000, time: "1 day ago" }, { bidder: "Chicago_Development", amount: 5400000, time: "2 days ago" }, { bidder: "Asset_Management", amount: 5350000, time: "2 days ago" }, { bidder: "Real_Estate_Fund", amount: 5300000, time: "3 days ago" }] },
  { id: 6, title: "Historic Downtown Loft", location: "250 Main Street, San Francisco, CA", image: "https://cdn.b12.io/client_media/MMT7mwJl/ff2be1f6-4fe9-11f1-8807-0242ac110002-TlHd2b7TaBDpUd06NZ6Vd.jpg", minPrice: 900000, maxPrice: 1000000, highestBid: 950000, highestBidder: "SF_Loft_Lover", minimumIncrement: 5000, bidsCount: 9, timeRemaining: "4 days", bedrooms: 2, bathrooms: 2, sqft: 2200, yearBuilt: 1920, description: "Beautiful historic loft in San Francisco's arts district with exposed brick, high ceilings, and large windows. Original hardwood floors, renovated kitchen and bathrooms. Ground floor retail potential.", features: ["2 Bedrooms", "2 Bathrooms", "2,200 Sq Ft", "High Ceilings", "Exposed Brick", "Original Details", "Retail Space", "Arts District Location"], recentBids: [{ bidder: "SF_Loft_Lover", amount: 950000, time: "2 hours ago" }, { bidder: "Bay_Area_Investor", amount: 945000, time: "6 hours ago" }, { bidder: "Loft_Specialist", amount: 940000, time: "12 hours ago" }, { bidder: "Urban_Living", amount: 925000, time: "1 day ago" }, { bidder: "Vintage_Property", amount: 910000, time: "2 days ago" }] }
];
