"use client"
import * as React from "react"
import * as P from "@radix-ui/react-dropdown-menu"
import { CheckIcon, ChevronRightIcon, CircleIcon } from "lucide-react"
import { cn } from "@/lib/utils"
const DropdownMenu=P.Root,DropdownMenuPortal=P.Portal,DropdownMenuTrigger=P.Trigger,DropdownMenuGroup=P.Group,DropdownMenuRadioGroup=P.RadioGroup,DropdownMenuSub=P.Sub
function DropdownMenuContent({className,sideOffset=4,...props}:React.ComponentProps<typeof P.Content>){return <P.Portal><P.Content sideOffset={sideOffset} className={cn("bg-popover text-popover-foreground z-50 min-w-32 rounded-md border p-1 shadow-md",className)} {...props}/></P.Portal>}
function DropdownMenuItem({className,inset,variant="default",...props}:React.ComponentProps<typeof P.Item>&{inset?:boolean;variant?:"default"|"destructive"}){return <P.Item data-inset={inset} data-variant={variant} className={cn("focus:bg-accent flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[inset]:pl-8",className)} {...props}/>}
function DropdownMenuCheckboxItem({className,children,checked,...props}:React.ComponentProps<typeof P.CheckboxItem>){return <P.CheckboxItem className={cn("focus:bg-accent relative flex cursor-default items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden select-none",className)} checked={checked} {...props}><span className="absolute left-2"><P.ItemIndicator><CheckIcon className="size-4"/></P.ItemIndicator></span>{children}</P.CheckboxItem>}
function DropdownMenuRadioItem({className,children,...props}:React.ComponentProps<typeof P.RadioItem>){return <P.RadioItem className={cn("focus:bg-accent relative flex cursor-default items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden select-none",className)} {...props}><span className="absolute left-2"><P.ItemIndicator><CircleIcon className="size-2 fill-current"/></P.ItemIndicator></span>{children}</P.RadioItem>}
function DropdownMenuLabel({className,inset,...props}:React.ComponentProps<typeof P.Label>&{inset?:boolean}){return <P.Label data-inset={inset} className={cn("px-2 py-1.5 text-sm font-medium data-[inset]:pl-8",className)} {...props}/>}
function DropdownMenuSeparator({className,...props}:React.ComponentProps<typeof P.Separator>){return <P.Separator className={cn("bg-border -mx-1 my-1 h-px",className)} {...props}/>}
function DropdownMenuShortcut({className,...props}:React.ComponentProps<"span">){return <span className={cn("text-muted-foreground ml-auto text-xs tracking-widest",className)} {...props}/>}
function DropdownMenuSubTrigger({className,inset,children,...props}:React.ComponentProps<typeof P.SubTrigger>&{inset?:boolean}){return <P.SubTrigger data-inset={inset} className={cn("focus:bg-accent flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[inset]:pl-8",className)} {...props}>{children}<ChevronRightIcon className="ml-auto size-4"/></P.SubTrigger>}
function DropdownMenuSubContent({className,...props}:React.ComponentProps<typeof P.SubContent>){return <P.SubContent className={cn("bg-popover text-popover-foreground z-50 min-w-32 rounded-md border p-1 shadow-lg",className)} {...props}/>}
export {DropdownMenu,DropdownMenuPortal,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuGroup,DropdownMenuLabel,DropdownMenuItem,DropdownMenuCheckboxItem,DropdownMenuRadioGroup,DropdownMenuRadioItem,DropdownMenuSeparator,DropdownMenuShortcut,DropdownMenuSub,DropdownMenuSubTrigger,DropdownMenuSubContent}
