"use client"
import * as React from "react"
import * as P from "@radix-ui/react-menubar"
import { CheckIcon,ChevronRightIcon,CircleIcon } from "lucide-react"
import { cn } from "@/lib/utils"
const MenubarMenu=P.Menu,MenubarGroup=P.Group,MenubarPortal=P.Portal,MenubarRadioGroup=P.RadioGroup,MenubarSub=P.Sub
function Menubar({className,...props}:React.ComponentProps<typeof P.Root>){return <P.Root className={cn("bg-background flex h-9 items-center gap-1 rounded-md border p-1 shadow-xs",className)} {...props}/>}
function MenubarTrigger({className,...props}:React.ComponentProps<typeof P.Trigger>){return <P.Trigger className={cn("focus:bg-accent flex items-center rounded-sm px-2 py-1 text-sm font-medium outline-hidden select-none",className)} {...props}/>}
function MenubarContent({className,align="start",alignOffset=-4,sideOffset=8,...props}:React.ComponentProps<typeof P.Content>){return <MenubarPortal><P.Content align={align} alignOffset={alignOffset} sideOffset={sideOffset} className={cn("bg-popover text-popover-foreground z-50 min-w-48 overflow-hidden rounded-md border p-1 shadow-md",className)} {...props}/></MenubarPortal>}
function MenubarItem({className,inset,variant="default",...props}:React.ComponentProps<typeof P.Item>&{inset?:boolean;variant?:"default"|"destructive"}){return <P.Item data-inset={inset} data-variant={variant} className={cn("focus:bg-accent relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[inset]:pl-8",className)} {...props}/>}
function MenubarCheckboxItem({className,children,checked,...props}:React.ComponentProps<typeof P.CheckboxItem>){return <P.CheckboxItem className={cn("focus:bg-accent relative flex cursor-default items-center gap-2 rounded-xs py-1.5 pr-2 pl-8 text-sm",className)} checked={checked} {...props}><span className="absolute left-2"><P.ItemIndicator><CheckIcon className="size-4"/></P.ItemIndicator></span>{children}</P.CheckboxItem>}
function MenubarRadioItem({className,children,...props}:React.ComponentProps<typeof P.RadioItem>){return <P.RadioItem className={cn("focus:bg-accent relative flex cursor-default items-center gap-2 rounded-xs py-1.5 pr-2 pl-8 text-sm",className)} {...props}><span className="absolute left-2"><P.ItemIndicator><CircleIcon className="size-2 fill-current"/></P.ItemIndicator></span>{children}</P.RadioItem>}
function MenubarLabel({className,inset,...props}:React.ComponentProps<typeof P.Label>&{inset?:boolean}){return <P.Label data-inset={inset} className={cn("px-2 py-1.5 text-sm font-medium data-[inset]:pl-8",className)} {...props}/>}
function MenubarSeparator({className,...props}:React.ComponentProps<typeof P.Separator>){return <P.Separator className={cn("bg-border -mx-1 my-1 h-px",className)} {...props}/>}
function MenubarShortcut({className,...props}:React.ComponentProps<"span">){return <span className={cn("text-muted-foreground ml-auto text-xs tracking-widest",className)} {...props}/>}
function MenubarSubTrigger({className,inset,children,...props}:React.ComponentProps<typeof P.SubTrigger>&{inset?:boolean}){return <P.SubTrigger data-inset={inset} className={cn("focus:bg-accent flex cursor-default items-center rounded-sm px-2 py-1.5 text-sm data-[inset]:pl-8",className)} {...props}>{children}<ChevronRightIcon className="ml-auto h-4 w-4"/></P.SubTrigger>}
function MenubarSubContent({className,...props}:React.ComponentProps<typeof P.SubContent>){return <P.SubContent className={cn("bg-popover text-popover-foreground z-50 min-w-32 rounded-md border p-1 shadow-lg",className)} {...props}/>}
export {Menubar,MenubarPortal,MenubarMenu,MenubarTrigger,MenubarContent,MenubarGroup,MenubarSeparator,MenubarLabel,MenubarItem,MenubarShortcut,MenubarCheckboxItem,MenubarRadioGroup,MenubarRadioItem,MenubarSub,MenubarSubTrigger,MenubarSubContent}
