"use client"
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import { PanelLeftIcon } from "lucide-react"
import { useIsMobile } from "@/hooks/use-mobile"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
const SIDEBAR_WIDTH="16rem", SIDEBAR_WIDTH_MOBILE="18rem", SIDEBAR_WIDTH_ICON="3rem"
type SidebarContextProps={state:"expanded"|"collapsed";open:boolean;setOpen:(open:boolean)=>void;openMobile:boolean;setOpenMobile:(open:boolean)=>void;isMobile:boolean;toggleSidebar:()=>void}
const SidebarContext=React.createContext<SidebarContextProps|null>(null)
function useSidebar(){const c=React.useContext(SidebarContext); if(!c) throw new Error("useSidebar must be used within a SidebarProvider."); return c}
function SidebarProvider({defaultOpen=true,open:openProp,onOpenChange:setOpenProp,className,style,children,...props}:React.ComponentProps<"div">&{defaultOpen?:boolean;open?:boolean;onOpenChange?:(open:boolean)=>void}){const isMobile=useIsMobile(); const [openMobile,setOpenMobile]=React.useState(false); const [_open,_setOpen]=React.useState(defaultOpen); const open=openProp??_open; const setOpen=React.useCallback((v:boolean)=>{setOpenProp?setOpenProp(v):_setOpen(v)},[setOpenProp]); const toggleSidebar=React.useCallback(()=>isMobile?setOpenMobile(o=>!o):setOpen(!open),[isMobile,open,setOpen]); const state=open?"expanded":"collapsed"; return <SidebarContext.Provider value={{state,open,setOpen,openMobile,setOpenMobile,isMobile,toggleSidebar}}><TooltipProvider delayDuration={0}><div style={{"--sidebar-width":SIDEBAR_WIDTH,"--sidebar-width-icon":SIDEBAR_WIDTH_ICON,...style} as React.CSSProperties} className={cn("group/sidebar-wrapper flex min-h-svh w-full",className)} {...props}>{children}</div></TooltipProvider></SidebarContext.Provider>}
function Sidebar({side="left",variant="sidebar",collapsible="offcanvas",className,children,...props}:React.ComponentProps<"div">&{side?:"left"|"right";variant?:"sidebar"|"floating"|"inset";collapsible?:"offcanvas"|"icon"|"none"}){const {isMobile,state,openMobile,setOpenMobile}=useSidebar(); if(collapsible==="none") return <div className={cn("bg-sidebar text-sidebar-foreground flex h-full w-(--sidebar-width) flex-col",className)} {...props}>{children}</div>; if(isMobile) return <Sheet open={openMobile} onOpenChange={setOpenMobile}><SheetContent className="bg-sidebar text-sidebar-foreground w-(--sidebar-width) p-0 [&>button]:hidden" style={{"--sidebar-width":SIDEBAR_WIDTH_MOBILE} as React.CSSProperties} side={side}><SheetHeader className="sr-only"><SheetTitle>Sidebar</SheetTitle><SheetDescription>Displays the mobile sidebar.</SheetDescription></SheetHeader><div className="flex h-full w-full flex-col">{children}</div></SheetContent></Sheet>; return <div className="group peer text-sidebar-foreground hidden md:block" data-state={state} data-collapsible={state==="collapsed"?collapsible:""} data-variant={variant} data-side={side}><div className="relative w-(--sidebar-width) bg-transparent transition-[width] duration-200"/><div className={cn("fixed inset-y-0 z-10 hidden h-svh w-(--sidebar-width) md:flex",side==="left"?"left-0":"right-0",className)} {...props}><div className="bg-sidebar flex h-full w-full flex-col">{children}</div></div></div>}
function SidebarTrigger({className,onClick,...props}:React.ComponentProps<typeof Button>){const {toggleSidebar}=useSidebar();return <Button variant="ghost" size="icon" className={cn("size-7",className)} onClick={(e)=>{onClick?.(e);toggleSidebar()}} {...props}><PanelLeftIcon/><span className="sr-only">Toggle Sidebar</span></Button>}
function SidebarRail({className,...props}:React.ComponentProps<"button">){const {toggleSidebar}=useSidebar();return <button aria-label="Toggle Sidebar" tabIndex={-1} onClick={toggleSidebar} className={cn("absolute inset-y-0 z-20 hidden w-4 sm:flex",className)} {...props}/>}
function SidebarInset({className,...props}:React.ComponentProps<"main">){return <main className={cn("bg-background relative flex w-full flex-1 flex-col",className)} {...props}/>}
function SidebarInput({className,...props}:React.ComponentProps<typeof Input>){return <Input className={cn("bg-background h-8 w-full shadow-none",className)} {...props}/>}
function SidebarHeader({className,...props}:React.ComponentProps<"div">){return <div className={cn("flex flex-col gap-2 p-2",className)} {...props}/>}
function SidebarFooter({className,...props}:React.ComponentProps<"div">){return <div className={cn("flex flex-col gap-2 p-2",className)} {...props}/>}
function SidebarSeparator({className,...props}:React.ComponentProps<typeof Separator>){return <Separator className={cn("bg-sidebar-border mx-2 w-auto",className)} {...props}/>}
function SidebarContent({className,...props}:React.ComponentProps<"div">){return <div className={cn("flex min-h-0 flex-1 flex-col gap-2 overflow-auto",className)} {...props}/>}
function SidebarGroup({className,...props}:React.ComponentProps<"div">){return <div className={cn("relative flex w-full min-w-0 flex-col p-2",className)} {...props}/>}
function SidebarGroupLabel({className,asChild=false,...props}:React.ComponentProps<"div">&{asChild?:boolean}){const Comp=asChild?Slot:"div";return <Comp className={cn("text-sidebar-foreground/70 flex h-8 shrink-0 items-center rounded-md px-2 text-xs font-medium",className)} {...props}/>}
function SidebarGroupAction({className,asChild=false,...props}:React.ComponentProps<"button">&{asChild?:boolean}){const Comp=asChild?Slot:"button";return <Comp className={cn("text-sidebar-foreground absolute top-3.5 right-3 flex aspect-square w-5 items-center justify-center rounded-md",className)} {...props}/>}
function SidebarGroupContent({className,...props}:React.ComponentProps<"div">){return <div className={cn("w-full text-sm",className)} {...props}/>}
function SidebarMenu({className,...props}:React.ComponentProps<"ul">){return <ul className={cn("flex w-full min-w-0 flex-col gap-1",className)} {...props}/>}
function SidebarMenuItem({className,...props}:React.ComponentProps<"li">){return <li className={cn("group/menu-item relative",className)} {...props}/>}
const sidebarMenuButtonVariants=cva("peer/menu-button flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left text-sm outline-hidden hover:bg-sidebar-accent hover:text-sidebar-accent-foreground",{variants:{variant:{default:"",outline:"bg-background shadow"},size:{default:"h-8 text-sm",sm:"h-7 text-xs",lg:"h-12 text-sm"}},defaultVariants:{variant:"default",size:"default"}})
function SidebarMenuButton({asChild=false,isActive=false,variant="default",size="default",tooltip,className,...props}:React.ComponentProps<"button">&{asChild?:boolean;isActive?:boolean;tooltip?:string|React.ComponentProps<typeof TooltipContent>}&VariantProps<typeof sidebarMenuButtonVariants>){const Comp=asChild?Slot:"button";const {isMobile,state}=useSidebar(); const button=<Comp data-active={isActive} className={cn(sidebarMenuButtonVariants({variant,size}),className)} {...props}/>; if(!tooltip)return button; if(typeof tooltip==="string") tooltip={children:tooltip}; return <Tooltip><TooltipTrigger asChild>{button}</TooltipTrigger><TooltipContent side="right" align="center" hidden={state!=="collapsed"||isMobile} {...tooltip}/></Tooltip>}
function SidebarMenuAction({className,asChild=false,...props}:React.ComponentProps<"button">&{asChild?:boolean;showOnHover?:boolean}){const Comp=asChild?Slot:"button";return <Comp className={cn("absolute top-1.5 right-1 flex aspect-square w-5 items-center justify-center rounded-md",className)} {...props}/>}
function SidebarMenuBadge({className,...props}:React.ComponentProps<"div">){return <div className={cn("pointer-events-none absolute right-1 flex h-5 min-w-5 items-center justify-center rounded-md px-1 text-xs font-medium",className)} {...props}/>}
function SidebarMenuSkeleton({className,showIcon=false,...props}:React.ComponentProps<"div">&{showIcon?:boolean}){return <div className={cn("flex h-8 items-center gap-2 rounded-md px-2",className)} {...props}>{showIcon&&<Skeleton className="size-4 rounded-md"/>}<Skeleton className="h-4 flex-1"/></div>}
function SidebarMenuSub({className,...props}:React.ComponentProps<"ul">){return <ul className={cn("border-sidebar-border mx-3.5 flex min-w-0 flex-col gap-1 border-l px-2.5 py-0.5",className)} {...props}/>}
function SidebarMenuSubItem({className,...props}:React.ComponentProps<"li">){return <li className={cn("group/menu-sub-item relative",className)} {...props}/>}
function SidebarMenuSubButton({asChild=false,size="md",isActive=false,className,...props}:React.ComponentProps<"a">&{asChild?:boolean;size?:"sm"|"md";isActive?:boolean}){const Comp=asChild?Slot:"a";return <Comp data-size={size} data-active={isActive} className={cn("flex h-7 min-w-0 items-center gap-2 overflow-hidden rounded-md px-2 text-sm hover:bg-sidebar-accent",size==="sm"&&"text-xs",className)} {...props}/>}
export {Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupAction,SidebarGroupContent,SidebarGroupLabel,SidebarHeader,SidebarInput,SidebarInset,SidebarMenu,SidebarMenuAction,SidebarMenuBadge,SidebarMenuButton,SidebarMenuItem,SidebarMenuSkeleton,SidebarMenuSub,SidebarMenuSubButton,SidebarMenuSubItem,SidebarProvider,SidebarRail,SidebarSeparator,SidebarTrigger,useSidebar}
